export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';